### ISSUE TITLE
0.2.12 broken on Node versions prior to Node 6 due to use of default function parameters

### ISSUE THREAD

**Issue by northerncodemky** [shevchenkos/DynamoDbBackUp#31]
Commit 2cb388d0e411892f159cf91e63d6e7f5fa5748f4 introduces default parameters on the ``backup`` function in dbRecord.js

This is not support in Node versions prior to 6 so this consequently doesn't work (and there is no engines field on the package.json to inform of this at install time).

**Comment by shevchenkos** [comment]
Made quick fix #32
