### ISSUE TITLE
No records to process

### ISSUE THREAD

**Issue by infigoKriti** [shevchenkos/DynamoDbBackUp#42]
Invoking the lambda function after deploying it and deploying the event results in "no records to process" as response though there are objects in the dynamodb. However, using gulp incremental backup works fine.

**Comment by shevchenkos** [comment]
Hi, @infigoKriti.
How do you invoke lambda function?
Is it incremental backup? Because the sentence 'However, using gulp incremental backup works fine.' confused me.

**Comment by infigoKriti** [comment]
I tried to use the aws lambda for dynamoDB backup and push it into S3 bucket. So I deployed AWS Lambda, deployed AWS Lambda event and tried invoking the created lambda function from aws cli. The response I got is "no records to process" . Also, no backup was pushed into the S3 bucket.

**Comment by infigoKriti** [comment]
Hi,
I am trying to create a lambda which backs up Dynamo DB and pushes it into
a s3 bucket. So I deployed the lambda function using gulp , deployed AWS
lambda event and tried to invoke lambda from AWS cli. However , no backup
is found in my s3 bucket and the response I get is "no records to process".

Regards,
Kriti Mantri

**Comment by shevchenkos** [comment]
Ok, I got it. 
Please, try to add new record or modify existing one in DynamoDB Table.
Also check that DynamoDB Stream is enabled.

**Comment by infigoKriti** [comment]
It works just fine now. Thanks.
Is it possible to use the same Lambda for : 
1)full backup 
2)multiple tables?

**Comment by shevchenkos** [comment]
Nice questions.
1. Definitely not. Full backup works through gulp task.
2. Need to test this case.
